// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { IconButton, IconButtonKind } from "icon-button.slint";
import { IconSet } from "@lucide";
import { PageTitle } from "page-header.slint";
import { UiState } from "../ui-state.slint";

export component ConversionQueueToolbar inherits HorizontalLayout {
    alignment: space-between;
    height: 38px;

    PageTitle {
        title: "Conversion queue";
    }

    VerticalLayout {
        alignment: center;

        if UiState.conversion-queue.length > 0: IconButton {
            icon: IconSet.X;
            label: "Cancel all conversions";
            kind: IconButtonKind.Primary;
            clicked => {
                UiState.confirming-cancel-all = true;
            }
        }
    }
}
