// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me> (TinyWiiBackupManager)
// SPDX-FileContributor: Modified by Jean-Matthieu Dechriste (TinyXbox360BackupManager)
// SPDX-License-Identifier: GPL-3.0-only

import { IconSet, IconDisplay } from "@lucide";
import { VerticalLine } from "vertical-line.slint";
import { IconButton } from "icon-button.slint";
import { DisplayedGame } from "../types.slint";
import { MyPalette } from "../styling.slint";
import { UiState } from "../ui-state.slint";
import { Message, Dispatcher } from "../messages.slint";

export component GameRow inherits Rectangle {
    in property <DisplayedGame> game;

    height: 24px;

    IconDisplay {
        x: 5px;
        y: 5px;
        icon: game.is-arcade ? IconSet.Gamepad2 : game.is-x360 ? IconSet.Disc3 : IconSet.Box;
        size: 14px;
        stroke: MyPalette.foreground;
    }

    Text {
        x: 5px + 14px + 5px;
        y: 5px;
        text: game.id.is-empty ? "\{game.title} [\{game.format}]" : "\{game.title} [\{game.id}]";
        overflow: elide;
    }

    Text {
        x: parent.width - 50px - self.preferred-width - 5px;
        y: 5px;
        text: "\{game.size-gib.to-fixed(2)} GiB";
    }

    VerticalLine {
        x: parent.width - 50px;
        y: 0px;
        height: 24px;
    }

    IconButton {
        x: parent.width - 49px;
        y: 0px;
        tooltip: "Game info";
        icon: IconSet.Info;
        height: 24px;
        width: 24px;
        squared: true;
        clicked => {
            UiState.current-game = game;
            Dispatcher.dispatch(Message.FetchGameDetails, game.path);
        }
    }

    VerticalLine {
        x: parent.width - 25px;
        y: 0px;
        height: 24px;
    }

    IconButton {
        x: parent.width - 24px;
        y: 0px;
        icon: IconSet.Trash;
        tooltip: "Delete game";
        height: 24px;
        width: 24px;
        squared: true;
        clicked => {
            UiState.game-to-delete = game;
        }
    }
}
