// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me> (TinyWiiBackupManager)
// SPDX-FileContributor: Modified by Jean-Matthieu Dechriste (TinyXbox360BackupManager)
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView, Palette } from "std-widgets.slint";
import { DisplayedGame } from "../types.slint";
import { IconSet, IconDisplay } from "@lucide";
import { Link } from "link.slint";
import { Card } from "card.slint";
import { HorizontalLine } from "horizontal-line.slint";
import { MyPalette } from "../styling.slint";
import { IconButton, IconButtonKind } from "icon-button.slint";
import { Modal } from "modal.slint";
import { UiState } from "../ui-state.slint";
import { Message, Dispatcher } from "../messages.slint";

export component GameInfoModal inherits Modal {
    VerticalLayout {
        alignment: stretch;

        VerticalLayout {
            alignment: space-between;

            VerticalLayout {
                padding: 20px;
                spacing: 10px;

                Text {
                    text: UiState.current-game.title;
                    font-size: 18px;
                    overflow: elide;
                }

                Link {
                    icon: IconSet.Folder;
                    label: "Path: \{UiState.current-game.path}";
                    uri: UiState.current-game.path;
                }
            }

            HorizontalLayout {
                alignment: space-between;
                padding-right: 10px;
                padding-left: 20px;

                VerticalLayout {
                    spacing: 5px;
                    alignment: center;
                    y: parent.height - self.height - 10px;

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.FileQuestionMark;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Format: \{UiState.current-game.format}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Tag;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Title ID: \{(UiState.current-game.id.is-empty ? "N/A" : UiState.current-game.id)}";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.Gamepad;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        if UiState.current-game.is-x360: Text {
                            text: "System: Xbox 360";
                        }

                        if !UiState.current-game.is-x360: Text {
                            text: "System: Original Xbox";
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;

                        IconDisplay {
                            icon: IconSet.HardDrive;
                            stroke: MyPalette.foreground;
                            size: 14px;
                        }

                        Text {
                            text: "Size: \{UiState.current-game.size-gib.to-fixed(2)} GiB";
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    Image {
                        source: UiState.current-game.cover;
                        height: 200px;
                    }
                }
            }

            VerticalLayout { }
        }

        VerticalLayout {
            height: self.min-height;

            HorizontalLine { }

            HorizontalLayout {
                alignment: space-between;

                VerticalLayout {
                    alignment: center;
                    padding-left: 15px;

                    if !UiState.current-game.id.is-empty: Link {
                        uri: "https://www.xboxunity.net/#/search/\{UiState.current-game.id}";
                        label: "XboxUnity page";
                    }
                }

                HorizontalLayout {
                    padding: 10px;
                    spacing: 10px;

                    IconButton {
                        label: "Close";
                        kind: IconButtonKind.Primary;
                        clicked => {
                            UiState.current-game = { };
                        }
                    }
                }
            }
        }
    }
}
