// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me> (TinyWiiBackupManager)
// SPDX-FileContributor: Modified by Jean-Matthieu Dechriste (TinyXbox360BackupManager)
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { Spinner } from "std-widgets.slint";
import { DisplayedGame } from "../types.slint";
import { IconButton } from "icon-button.slint";
import { IconSet, IconDisplay } from "@lucide";
import { MyPalette } from "../styling.slint";
import { UiState } from "../ui-state.slint";
import { Message, Dispatcher } from "../messages.slint";

export component GameCard inherits Card {
    in property <DisplayedGame> game;

    width: 172px;
    height: self.min-height;

    VerticalLayout {
        padding: 10px;
        spacing: 10px;

        HorizontalLayout {
            alignment: space-between;

            HorizontalLayout {
                spacing: 5px;

                IconDisplay {
                    icon: IconSet.Tag;
                    size: 13px;
                    stroke: MyPalette.foreground;
                }

                Text {
                    text: game.id.is-empty ? game.format : game.id;
                    wrap: no-wrap;
                }
            }

            Text {
                text: "\{game.size-gib.to-fixed(2)} GiB";
                wrap: no-wrap;
                horizontal-alignment: right;
            }
        }

        if game.cover.width > 0: Image {
            source: game.cover;
            height: 93px;
        }

        // Cover currently downloading: circular indicator.
        if game.cover.width == 0 && !game.id.is-empty && UiState.downloading-covers: VerticalLayout {
            height: 93px;
            alignment: center;

            HorizontalLayout {
                alignment: center;

                Spinner {
                    width: 48px;
                    height: 48px;
                    indeterminate: true;
                }
            }
        }

        // No cover available: neutral icon.
        if game.cover.width == 0 && (game.id.is-empty || !UiState.downloading-covers): VerticalLayout {
            height: 93px;
            alignment: center;

            HorizontalLayout {
                alignment: center;

                IconDisplay {
                    icon: IconSet.Image;
                    size: 48px;
                    stroke: MyPalette.foreground.transparentize(0.6);
                }
            }
        }

        Text {
            text: game.title;
            horizontal-alignment: center;
            wrap: no-wrap;
            overflow: elide;
        }

        HorizontalLayout {
            spacing: 5px;

            IconButton {
                label: "Info";
                icon: IconSet.Info;
                clicked => {
                    UiState.current-game = game;
                }
            }

            IconButton {
                width: self.height + 1px;
                icon: IconSet.Trash;
                tooltip: "Delete game";
                clicked => {
                    UiState.game-to-delete = game;
                }
            }
        }
    }
}
