// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { UiState } from "../ui-state.slint";
import { StyleMetrics } from "std-widgets.slint";
import { MyPalette } from "../styling.slint";
import { IconDisplay, Icon, IconSet } from "@lucide";
import { Message, Dispatcher } from "../messages.slint";

export component Link inherits Rectangle {
    in property <string> label;
    in property <string> uri;
    in property <Icon> icon: IconSet.Globe;

    height: 14px;
    width: 17px + t.width;

    IconDisplay {
        x: 0px;
        y: 0px;
        icon: icon;
        stroke: MyPalette.accent-background;
        size: 14px;
    }

    t := Text {
        x: 17px;
        y: (parent.height - self.height) / 2;
        text: label;
        color: MyPalette.accent-background;
        overflow: elide;
    }

    Rectangle {
        x: 1px;
        y: 15px;
        height: 1px;
        width: 15px + t.width;
        background: MyPalette.accent-background;
    }

    TouchArea {
        x: 0px;
        y: 0px;
        height: 14px;
        width: 17px + t.width;
        mouse-cursor: pointer;
        clicked => Dispatcher.dispatch(Message.OpenThat, uri);
    }
}
