// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { MyPalette } from "../styling.slint";
import { Card } from "card.slint";

export component Modal inherits Rectangle {
    in property <length> min-w: 300px;
    in property <length> max-w: 600px;
    in property <length> min-h: 0px;
    in property <length> max-h: 400px;
    in property <length> spacing: 0px;

    height: 100%;
    width: 100%;

    // block input in the main view
    TouchArea {
        x: 0px;
        y: 0px;
        width: root.width;
        height: root.height;
    }

    // darken the main view to signal that the input is blocked
    Rectangle {
        x: 0px;
        y: 0px;
        width: root.width;
        height: root.height;
        background: MyPalette.overlay;
    }

    // the actual modal, sized to fit its content within [min, max] bounds
    Card {
        width: max(min-w, min(max-w, body.preferred-width));
        height: max(min-h, min(max-h, body.preferred-height));

        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;

        body := VerticalLayout {
            spacing: root.spacing;
            alignment: start;
            vertical-stretch: 0;

            @children
        }
    }
}
