// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me>
// SPDX-License-Identifier: GPL-3.0-only

import { Card } from "card.slint";
import { IconButton } from "icon-button.slint";
import { IconSet, IconDisplay } from "@lucide";
import { MyPalette } from "../styling.slint";
import { UiState } from "../ui-state.slint";
import { Message, Dispatcher } from "../messages.slint";

export component Notifications inherits TouchArea {
    width: v.width;
    height: v.height;

    v := VerticalLayout {
        width: min(self.preferred-width, 400px);
        height: self.preferred-height;
        padding: 10px;
        spacing: 5px;

        for notification[i] in UiState.notifications: Card {
            min-height: 40px;

            h := HorizontalLayout {
                spacing: 10px;
                padding-left: 10px;
                padding-right: 10px;
                padding-top: 8px;
                padding-bottom: 8px;

                VerticalLayout {
                    alignment: start;
                    width: 14px;

                    IconDisplay {
                        icon: notification.critical ? IconSet.TriangleAlert : IconSet.Info;
                        size: 14px;
                        stroke: MyPalette.foreground;
                    }
                }

                Text {
                    text: notification.text;
                    wrap: word-wrap;
                    horizontal-stretch: 1;
                }

                VerticalLayout {
                    alignment: start;

                    IconButton {
                        icon: IconSet.X;
                        clicked => Dispatcher.dispatch(Message.CloseNotification, i);
                        rounded: true;
                        height: 24px;
                        width: 24px;
                    }
                }
            }
        }
    }
}
