// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me> (TinyWiiBackupManager)
// SPDX-FileContributor: Modified by Jean-Matthieu Dechriste (TinyXbox360BackupManager)
// SPDX-License-Identifier: GPL-3.0-only

import { MyPalette } from "styling.slint";
import { IconDisplay, IconSet } from "@lucide";
import { Link } from "components/link.slint";
import { Card } from "components/card.slint";
import { HorizontalLine } from "components/horizontal-line.slint";
import { UiState } from "ui-state.slint";

export component AboutPage inherits Rectangle {
    Card {
        width: 600px;
        height: self.min-height;
        x: parent.width / 2 - self.width / 2;
        y: parent.height / 2 - self.height / 2;

        VerticalLayout {
            padding: 20px;
            spacing: 10px;
            alignment: start;

            HorizontalLayout {
                padding: 10px;
                spacing: 10px;

                Image {
                    source: @image-url("../assets/TinyXbox360BackupManager-256x256.png");
                    width: 128px;
                    height: 128px;
                }

                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;
                    alignment: center;

                    Text {
                        text: "TinyXbox360BackupManager v\{UiState.app-version}";
                        font-size: 18px;
                        font-weight: 700;
                    }

                    Text {
                        text: "Copyright © 2026 Jean-Matthieu";
                    }

                    Link {
                        label: "github/jeanmatthieud";
                        uri: "https://github.com/jeanmatthieud";
                    }

                    Link {
                        label: "GPL-3.0-only";
                        uri: "https://www.gnu.org/licenses/gpl-3.0.html";
                        icon: IconSet.Scale;
                    }
                }
            }

            HorizontalLayout {
                spacing: 10px;

                VerticalLayout {
                    alignment: center;

                    IconDisplay {
                        icon: IconSet.TriangleAlert;
                        stroke: MyPalette.foreground;
                    }
                }

                Text {
                    text: "TinyXbox360BackupManager is intended strictly for legal backup use and is not affiliated with or endorsed by Microsoft. Use of TinyXbox360BackupManager for pirated or unauthorized copies of games is strictly prohibited.";
                    wrap: word-wrap;
                }
            }

            HorizontalLine { }

            HorizontalLayout {
                cross-axis-alignment: CrossAxisAlignment.center;
                
                IconDisplay {
                    icon: IconSet.Heart;
                    stroke: MyPalette.foreground;
                    size: 15px;
                }

                Text {
                    text: " Special thanks to";
                    font-size: 16px;
                }
            }

            HorizontalLayout {
                Link {
                    label: "Manuel Quarneti";
                    uri: "https://github.com/mq1";
                    icon: IconSet.Pointer;
                }

                Text {
                    text: " for TinyWiiBackupManager, which this app is based on.";
                }
            }

            HorizontalLayout {
                Link {
                    label: "iliazeus";
                    uri: "https://github.com/iliazeus/iso2god-rs";
                    icon: IconSet.Disc3;
                }

                Text {
                    text: " for iso2god-rs (ISO to GOD conversion).";
                }
            }

            HorizontalLayout {
                Link {
                    label: "antangelo";
                    uri: "https://github.com/antangelo/xdvdfs";
                    icon: IconSet.Box;
                }

                Text {
                    text: " for xdvdfs (XISO extraction).";
                }
            }

            HorizontalLayout {
                Link {
                    label: "XboxUnity";
                    uri: "https://www.xboxunity.net";
                    icon: IconSet.Image;
                }

                Text {
                    text: " for the covers and title updates database.";
                }
            }

            HorizontalLayout {
                Link {
                    label: "MobCat";
                    uri: "https://github.com/MobCat/MobCats-original-xbox-game-list";
                    icon: IconSet.Image;
                }

                Text {
                    text: " for the original Xbox game covers.";
                }
            }
        }
    }

    HorizontalLayout {
        width: self.min-width;
        height: self.min-height;

        x: parent.width - self.width - 15px;
        y: parent.height - self.height - 15px;

        spacing: 10px;

        Link {
            label: "Data directory";
            uri: UiState.data-dir;
            icon: IconSet.Folder;
        }

        Link {
            label: "Source code";
            uri: "https://github.com/jeanmatthieud/TinyXbox360BackupManager";
        }
    }
}
