// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me> (TinyWiiBackupManager)
// SPDX-FileContributor: Modified by Jean-Matthieu Dechriste (TinyXbox360BackupManager)
// SPDX-License-Identifier: GPL-3.0-only

import { ScrollView, Palette } from "std-widgets.slint";
import { IconSet } from "@lucide";
import { SettingCard } from "components/setting-card.slint";
import { PageHeader } from "components/page-header.slint";
import { UiState } from "ui-state.slint";
import { Message, Dispatcher } from "messages.slint";

export component SettingsPage inherits VerticalLayout {
    PageHeader {
        title: "Settings";
    }

    ScrollView {
        VerticalLayout {
            width: 100%;
            padding: 10px;
            padding-top: 0px;
            spacing: 10px;
            alignment: start;

            SettingCard {
                icon: IconSet.Trash;
                label: "Delete source ISOs when adding games";
                items: [{ value: "false", label: "No (recommended)" }, { value: "true", label: "Yes" }];
                active-item: UiState.config.remove-sources-games;
                set-property: Message.SetRemoveSourcesGames;
            }

            SettingCard {
                icon: IconSet.Package;
                label: "Xbox 360 storage format";
                items: [
                    { value: "God", label: "GOD (Games On Demand, recommended)" },
                    { value: "Xex", label: "XEX (extracted game folder)" }
                ];
                active-item: UiState.config.xbox360-format;
                set-property: Message.SetXbox360Format;
            }

            SettingCard {
                icon: IconSet.SunMoon;
                label: "Theme";
                items: [
                    { value: "System", label: "System (requires restart)" },
                    { value: "Light", label: "Light" },
                    { value: "Dark", label: "Dark" }
                ];
                active-item: UiState.config.theme-preference;
                set-property: Message.SetThemePreference;

                changed() => {
                    if UiState.config.theme-preference == "Light" {
                        Palette.color-scheme = ColorScheme.light;
                    } else if UiState.config.theme-preference == "Dark" {
                        Palette.color-scheme = ColorScheme.dark;
                    }
                }
            }

            SettingCard {
                icon: IconSet.Cable;
                label: "Reconnect to the last target on startup";
                items: [
                    { value: "Never", label: "Never" },
                    { value: "Always", label: "Always" },
                    { value: "FtpOnly", label: "Only if the last target was over FTP" },
                    { value: "UsbOnly", label: "Only if the last target was a USB drive" }
                ];
                active-item: UiState.config.auto-reconnect;
                set-property: Message.SetAutoReconnect;
            }
        }
    }
}
