// SPDX-FileCopyrightText: 2026 Manuel Quarneti <mq1@ik.me> (TinyWiiBackupManager)
// SPDX-FileContributor: Modified by Jean-Matthieu Dechriste (TinyXbox360BackupManager)
// SPDX-License-Identifier: GPL-3.0-only

import {
    DisplayedConfig,
    DisplayedDriveInfo,
    DisplayedGame,
    Notification,
    Page,
} from "types.slint";

export global UiState {
    in-out property <Page> current-page: Page.Games;
    in-out property <DisplayedGame> current-game;
    in-out property <DisplayedGame> game-to-delete;
    in-out property <bool> selecting-target: false;
    in-out property <bool> editing-ftp-target: false;

    in-out property <DisplayedConfig> config;
    in-out property <string> app-version;
    in-out property <string> data-dir;
    in-out property <DisplayedDriveInfo> drive-info;
    in-out property <[DisplayedGame]> games;
    in-out property <[Notification]> notifications;
    in-out property <[string]> conversion-queue;
    in-out property <[string]> games-to-add;
    in-out property <string> status;
    in-out property <string> latest-version;
    // True while downloading missing covers.
    in-out property <bool> downloading-covers: false;
    // True during target scan (cancellable).
    in-out property <bool> scanning: false;
}
